/*
 * Program: EECS 348 Assignment 2
 * Description: C program that prioritizes a CEO's emails using a MaxHeap.
 *              Emails are prioritized by sender category and then by date.
 * Inputs: EMAIL, NEXT, READ, and COUNT commands read from standard input.
 * Outputs: Displays the next highest-priority email and the current number
 *          of unread emails when requested.
 * Collaborators: None
 * Other Sources: Claude (original code used as basis), Gemini (original code that was compared with Claude),
 *                ChatGPT (assistance with prompting, analysis, improvements, testing, and comments)
 * Author: Nathan Lenahan
 * Creation Date: September 15, 2026
 * Revision Date: September 15, 2026
 * Revisions: Created the final program using Claude's generated code as the basis.
 *            Additional improvements were made for correctness, execution time,
 *            space complexity, and maintainability.
 */


// The following include statements are based on the original code generated by Claude
// The unused ctype.h library was removed during cleanup
#include <stdio.h>  // Includes standard input/output functions
#include <stdlib.h> // Includes memory allocation and program exit functions
#include <string.h> // Includes string handling functions

// The following constants are based on the original code generated by Claude
// MAX_SENDER and MAX_DATE were reduced to use less memory
#define MAX_LINE 1024          // Maximum size of an input line
#define MAX_SENDER 16          // Holds the longest sender category plus '\0'
#define MAX_SUBJECT 512        // Maximum space reserved for an email subject
#define MAX_DATE 11            // Holds MM-DD-YYYY plus '\0'
#define INITIAL_CAPACITY 16    // Starting capacity of the MaxHeap

// The following Email structure is based on the original code generated by Claude
// dateValue was changed from long to int to reduce memory usage
typedef struct { // Start of email structure
    char sender[MAX_SENDER];   // Stores the sender category
    char subject[MAX_SUBJECT]; // Stores the email subject
    char date[MAX_DATE];       // Stores the original date in MM-DD-YYYY format
    int categoryRank;          // Stores the numerical priority of the sender category
    int dateValue;             // Stores the date as YYYYMMDD for priority comparisons
} Email; // End of email structure

// The following MaxHeap structure is from the original code generated by Claude
typedef struct { // Starts the MaxHeap structure
    Email *data; // Points to the dynamic array that stores the emails
    int size; // Stores the current number of emails in the heap
    int capacity; // Stores the maximum number of emails the current array can hold
} MaxHeap; // Ends the MaxHeap structure

// The following trimNewline function is from the original code generated by Claude
static void trimNewline(char *s) { // Starts the trimNewline function
    size_t len = strlen(s); // Gets the current length of the input string

    while (len > 0 && (s[len - 1] == '\n' || s[len - 1] == '\r')) { // Checks for newline characters at the end of the string
        s[len - 1] = '\0'; // Replaces the newline character with the string terminator
        len--; // Decreases the stored length after removing a character
    } // Ends the while loop
} // Ends the trimNewline function

// The following categoryToRank function is from the original code generated by Claude
static int categoryToRank(const char *category) { // Starts the categoryToRank function
    if (strcmp(category, "Boss") == 0) return 5; // Gives Boss the highest priority
    if (strcmp(category, "Subordinate") == 0) return 4; // Gives Subordinate the second highest priority
    if (strcmp(category, "Peer") == 0) return 3; // Gives Peer the middle priority
    if (strcmp(category, "ImportantPerson") == 0) return 2; // Gives ImportantPerson the second lowest priority
    if (strcmp(category, "OtherPerson") == 0) return 1; // Gives OtherPerson the lowest priority
    return 0; // Returns 0 if the category does not match any expected value
} // Ends the categoryToRank function

// The following dateToValue function is based on the original code generated by Claude
// The return type was changed from long to int to reduce memory usage
static int dateToValue(const char *date) { // Starts the dateToValue function
    int month = 0, day = 0, year = 0; // Creates variables to store each part of the date

    if (sscanf(date, "%d-%d-%d", &month, &day, &year) != 3) { // Checks that all three parts of the date were read correctly
        return 0; // Returns 0 if the date is formatted incorrectly
    } // Ends the if statement

    return year * 10000 + month * 100 + day; // Converts the date into YYYYMMDD format for comparisons
} // Ends the dateToValue function

// The following heapInit function is from the original code generated by Claude
static void heapInit(MaxHeap *heap) { // Starts the heapInit function
    heap->capacity = INITIAL_CAPACITY; // Sets the starting capacity of the heap
    heap->size = 0; // Sets the starting number of emails to 0
    heap->data = (Email *)malloc(sizeof(Email) * heap->capacity); // Allocates memory for the starting email array

    if (heap->data == NULL) { // Checks if the memory allocation failed
        fprintf(stderr, "Error: could not allocate memory for heap.\n"); // Displays an error message
        exit(EXIT_FAILURE); // Ends the program because the heap could not be created
    } // Ends the if statement
} // Ends the heapInit function

// The following heapFree function is from the original code generated by Claude
static void heapFree(MaxHeap *heap) { // Starts the heapFree function
    free(heap->data); // Frees the memory used by the email array
    heap->data = NULL; // Removes the pointer to the freed memory
    heap->size = 0; // Resets the number of emails in the heap
    heap->capacity = 0; // Resets the heap capacity
} // Ends the heapFree function

// The following heapGrow function is from the original code generated by Claude
static void heapGrow(MaxHeap *heap) { // Starts the heapGrow function
    int newCapacity = heap->capacity * 2; // Doubles the current heap capacity
    Email *newData = (Email *)realloc(heap->data, sizeof(Email) * newCapacity); // Tries to resize the email array

    if (newData == NULL) { // Checks if the memory reallocation failed
        fprintf(stderr, "Error: could not grow heap memory.\n"); // Displays an error message
        exit(EXIT_FAILURE); // Ends the program because the heap could not be resized
    } // Ends the if statement

    heap->data = newData; // Updates the heap to point to the resized array
    heap->capacity = newCapacity; // Updates the stored capacity
} // Ends the heapGrow function

// The following hasHigherPriority function is from the original code generated by Claude
static int hasHigherPriority(const Email *a, const Email *b) { // Starts the hasHigherPriority function
    if (a->categoryRank != b->categoryRank) { // Checks if the emails have different sender priorities
        return a->categoryRank > b->categoryRank; // Returns true if email a has the higher sender priority
    } // Ends the if statement

    return a->dateValue > b->dateValue; // If sender priorities match, returns true if email a is newer
} // Ends the hasHigherPriority function

// The following swapEmails function is from the original code generated by Claude
static void swapEmails(Email *a, Email *b) { // Starts the swapEmails function
    Email temp = *a; // Temporarily stores email a
    *a = *b; // Replaces email a with email b
    *b = temp; // Replaces email b with the original email a
} // Ends the swapEmails function

// The following siftUp function is from the original code generated by Claude
static void siftUp(MaxHeap *heap, int idx) { // Starts the siftUp function
    while (idx > 0) { // Loops while the email is not at the root of the heap
        int parent = (idx - 1) / 2; // Finds the index of the current email's parent

        if (hasHigherPriority(&heap->data[idx], &heap->data[parent])) { // Checks if the current email has higher priority than its parent
            swapEmails(&heap->data[idx], &heap->data[parent]); // Swaps the current email with its parent
            idx = parent; // Moves the current index up to the parent's position
        } else { // Runs if the current email is already in the correct position
            break; // Stops moving the email up the heap
        } // Ends the if-else statement
    } // Ends the while loop
} // Ends the siftUp function

// The following siftDown function is from the original code generated by Claude
static void siftDown(MaxHeap *heap, int idx) { // Starts the siftDown function
    while (1) { // Continues looping until the email is in the correct position
        int left = 2 * idx + 1; // Finds the index of the left child
        int right = 2 * idx + 2; // Finds the index of the right child
        int largest = idx; // Assumes the current email has the highest priority

        if (left < heap->size && hasHigherPriority(&heap->data[left], &heap->data[largest])) { // Checks if the left child has higher priority
            largest = left; // Sets the left child as the highest-priority email
        } // Ends the first if statement

        if (right < heap->size && hasHigherPriority(&heap->data[right], &heap->data[largest])) { // Checks if the right child has higher priority
            largest = right; // Sets the right child as the highest-priority email
        } // Ends the second if statement

        if (largest == idx) { // Checks if the current email is already in the correct position
            break; // Stops the loop if no swap is needed
        } // Ends the if statement

        swapEmails(&heap->data[idx], &heap->data[largest]); // Swaps the current email with the higher-priority child
        idx = largest; // Moves the current index down to the child's position
    } // Ends the while loop
} // Ends the siftDown function

// The following heapInsert function is from the original code generated by Claude
static void heapInsert(MaxHeap *heap, const char *sender, const char *subject, const char *date) { // Starts the heapInsert function
    if (heap->size == heap->capacity) { // Checks if the heap is full
        heapGrow(heap); // Doubles the capacity of the heap if more space is needed
    } // Ends the if statement

    Email *slot = &heap->data[heap->size]; // Points to the next available position in the heap
    strncpy(slot->sender, sender, MAX_SENDER - 1); // Copies the sender into the new email
    slot->sender[MAX_SENDER - 1] = '\0'; // Makes sure the sender string ends properly
    strncpy(slot->subject, subject, MAX_SUBJECT - 1); // Copies the subject into the new email
    slot->subject[MAX_SUBJECT - 1] = '\0'; // Makes sure the subject string ends properly
    strncpy(slot->date, date, MAX_DATE - 1); // Copies the date into the new email
    slot->date[MAX_DATE - 1] = '\0'; // Makes sure the date string ends properly
    slot->categoryRank = categoryToRank(sender); // Converts the sender category into its priority rank
    slot->dateValue = dateToValue(date); // Converts the date into a numerical value for comparisons

    heap->size++; // Increases the number of emails stored in the heap
    siftUp(heap, heap->size - 1); // Moves the new email up until the MaxHeap order is restored
} // Ends the heapInsert function

// The following heapPeek function is based on the original code generated by Claude
// It was modified to return a pointer instead of copying the entire Email structure
static const Email *heapPeek(const MaxHeap *heap) { // Starts the heapPeek function
    if (heap->size == 0) { // Checks if there are no emails in the heap
        return NULL; // Returns NULL if the heap is empty
    } // Ends the if statement

    return &heap->data[0]; // Returns a pointer to the highest-priority email
} // Ends the heapPeek function

// The following heapExtractMax function is from the original code generated by Claude
static int heapExtractMax(MaxHeap *heap) { // Starts the heapExtractMax function
    if (heap->size == 0) { // Checks if the heap is already empty
        return 0; // Returns 0 because there is no email to remove
    } // Ends the if statement

    heap->data[0] = heap->data[heap->size - 1]; // Moves the last email to the root
    heap->size--; // Decreases the number of emails in the heap

    if (heap->size > 0) { // Checks if there are still emails left in the heap
        siftDown(heap, 0); // Moves the new root down until the MaxHeap order is restored
    } // Ends the if statement

    return 1; // Returns 1 to show that an email was successfully removed
} // Ends the heapExtractMax function

// The following handleEmailCommand function is from the original code generated by Claude
static void handleEmailCommand(MaxHeap *heap, char *rest) { // Starts the handleEmailCommand function
    char *firstComma = strchr(rest, ','); // Finds the first comma in the EMAIL command
    char *lastComma = strrchr(rest, ','); // Finds the last comma in the EMAIL command

    if (firstComma == NULL || lastComma == NULL || firstComma == lastComma) { // Checks if the EMAIL command is missing required commas
        fprintf(stderr, "Warning: malformed EMAIL command ignored: %s\n", rest); // Displays a warning for an incorrectly formatted command
        return; // Stops processing the invalid EMAIL command
    } // Ends the if statement

    size_t categoryLen = (size_t)(firstComma - rest); // Finds the length of the sender category
    char category[MAX_SENDER]; // Creates an array to store the sender category

    if (categoryLen >= MAX_SENDER) { // Checks if the sender category is too long for the array
        categoryLen = MAX_SENDER - 1; // Shortens the length so there is room for '\0'
    } // Ends the if statement

    strncpy(category, rest, categoryLen); // Copies the sender category into the array
    category[categoryLen] = '\0'; // Adds the string terminator to the sender category

    char date[MAX_DATE]; // Creates an array to store the email date
    strncpy(date, lastComma + 1, MAX_DATE - 1); // Copies the date after the last comma
    date[MAX_DATE - 1] = '\0'; // Makes sure the date string ends properly

    size_t subjectLen = (size_t)(lastComma - (firstComma + 1)); // Finds the length of the subject line
    char subject[MAX_SUBJECT]; // Creates an array to store the subject

    if (subjectLen >= MAX_SUBJECT) { // Checks if the subject is too long for the array
        subjectLen = MAX_SUBJECT - 1; // Shortens the length so there is room for '\0'
    } // Ends the if statement

    strncpy(subject, firstComma + 1, subjectLen); // Copies the subject into the array
    subject[subjectLen] = '\0'; // Adds the string terminator to the subject

    heapInsert(heap, category, subject, date); // Inserts the completed email into the MaxHeap
} // Ends the handleEmailCommand function

// The following handleNextCommand function is based on the original code generated by Claude
// It was modified to use the pointer returned by heapPeek instead of copying the entire Email structure
static void handleNextCommand(MaxHeap *heap) { // Starts the handleNextCommand function
    const Email *top = heapPeek(heap); // Gets a pointer to the highest-priority email

    if (top == NULL) { // Checks if there are no emails in the heap
        printf("\nNo emails to read.\n"); // Tells the user there are no emails to display
        return; // Ends the function because there is no email to show
    } // Ends the if statement

    printf("\nNext email:\n"); // Displays the heading for the next email
    printf("\tSender: %s\n", top->sender); // Displays the sender of the highest-priority email
    printf("\tSubject: %s\n", top->subject); // Displays the subject of the highest-priority email
    printf("\tDate: %s\n", top->date); // Displays the date of the highest-priority email
} // Ends the handleNextCommand function

// The following handleReadCommand function is from the original code generated by Claude
static void handleReadCommand(MaxHeap *heap) { // Starts the handleReadCommand function
    heapExtractMax(heap); // Removes the highest-priority email from the MaxHeap
} // Ends the handleReadCommand function

// The following handleCountCommand function is from the original code generated by Claude
static void handleCountCommand(MaxHeap *heap) { // Starts the handleCountCommand function
    if (heap->size == 1) { // Checks if there is exactly one unread email
        printf("There is 1 email to read.\n"); // Displays the singular message for one email
    } else { // Runs when there are zero or multiple unread emails
        printf("There are %d emails to read.\n", heap->size); // Displays the current number of unread emails
    } // Ends the if-else statement
} // Ends the handleCountCommand function

// The following main function is from the original code generated by Claude
int main(void) { // Starts the main function
    MaxHeap heap; // Creates the MaxHeap that will store all unread emails
    heapInit(&heap); // Initializes the MaxHeap

    char line[MAX_LINE]; // Creates an array to store each line of input

    while (fgets(line, sizeof(line), stdin) != NULL) { // Reads and processes each input line until the end of the file
        trimNewline(line); // Removes any newline characters from the end of the input

        if (line[0] == '\0') { // Checks if the input line is empty
            continue; // Skips the empty line and reads the next command
        } // Ends the if statement

        if (strncmp(line, "EMAIL ", 6) == 0) { // Checks if the command is EMAIL
            handleEmailCommand(&heap, line + 6); // Processes the email information after "EMAIL "
        } else if (strcmp(line, "NEXT") == 0) { // Checks if the command is NEXT
            handleNextCommand(&heap); // Displays the highest-priority unread email
        } else if (strcmp(line, "READ") == 0) { // Checks if the command is READ
            handleReadCommand(&heap); // Removes the highest-priority unread email
        } else if (strcmp(line, "COUNT") == 0) { // Checks if the command is COUNT
            handleCountCommand(&heap); // Displays the current number of unread emails
        } else { // Runs if the input does not match one of the expected commands
            fprintf(stderr, "Warning: unrecognized command ignored: %s\n", line); // Displays a warning for an unknown command
        } // Ends the command if-else structure
    } // Ends the input loop

    heapFree(&heap); // Frees the memory used by the MaxHeap
    return 0; // Ends the program successfully
} // Ends the main function